[package]
name = "rf2e"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["derive"] }
strum = { version = "0.27.1", features = ["derive"] }
